site_name: 我の温馨小窝
site_url: https://tech-arima.github.io

######### 导航栏
nav:
  - 博客:
    - Blog/index.md
    - 第一个: Blog/posts/First post.md

  
  - 随笔:
    - Diary/index.md



######### 主题设置
theme:
  name: material
  logo: images/logo.png

  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:

        icon: material/weather-night

        name: 切换至夜间模式
  # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    #上面导航栏
    - navigation.tabs
    #返回顶部
    - navigation.top
    #导航路径
    - navigation.path
    #添加介绍页
    - navigation.indexes

  language: zh

#############一些插件
plugins:


# 添加外部链接
extra:
  social: # icons
    - name: GitHub | Tech-Arima
      icon: fontawesome/brands/github
      link: https://github.com/Tech-Arima
    - name: Bilibili | 花樱茉莉
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/280082543


copyright: Yxfan_Arima CC-BY-4.0
